--
-- PostgreSQL database dump
--

-- Dumped from database version 17.1
-- Dumped by pg_dump version 17.1

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: customer; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.customer (
    id bigint NOT NULL,
    admin boolean NOT NULL,
    birth_date date,
    email character varying(255),
    month_visits integer NOT NULL,
    name character varying(255),
    password character varying(255),
    phone character varying(255),
    rut character varying(255)
);


ALTER TABLE public.customer OWNER TO postgres;

--
-- Name: customer_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.customer ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.customer_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: kart; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.kart (
    id bigint NOT NULL,
    available boolean NOT NULL,
    code character varying(255),
    model character varying(255)
);


ALTER TABLE public.kart OWNER TO postgres;

--
-- Name: kart_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.kart ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.kart_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: reservation; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.reservation (
    id bigint NOT NULL,
    group_detail text,
    laps_or_time integer NOT NULL,
    number_people integer NOT NULL,
    reservation_date timestamp(6) without time zone,
    rut_user character varying(255),
    ruts_users character varying(255)
);


ALTER TABLE public.reservation OWNER TO postgres;

--
-- Name: reservation_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.reservation ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.reservation_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: customer customer_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.customer
    ADD CONSTRAINT customer_pkey PRIMARY KEY (id);


--
-- Name: kart kart_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.kart
    ADD CONSTRAINT kart_pkey PRIMARY KEY (id);


--
-- Name: reservation reservation_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.reservation
    ADD CONSTRAINT reservation_pkey PRIMARY KEY (id);


--
-- PostgreSQL database dump complete
--


-- Dump de base de datos para KartingRM

-- Tabla customer
INSERT INTO public.customer (admin, birth_date, email, month_visits, name, password, phone, rut)
VALUES
    (true, '1990-01-01', 'camila.lagos.l@usach.cl', 0, 'Admin User', '123', '123456789', '21292380-k'),
    (false, '1995-05-15', 'camila.lagos.l@usach.cl', 2, 'User One', 'user1', '987654321', '11111111-1'),
    (false, '1998-08-20', 'camila.lagos.l@usach.cl', 7, 'User Two', 'user2', '564738291', '22222222-2'),
    (false, '1992-03-10', 'camila.lagos.l@usach.cl', 10, 'User Three', 'user2', '112233445', '33333333-3');

-- Tabla kart
INSERT INTO public.kart (available, code, model)
VALUES
    (true, 'K001', 'Sodikart RT8'),
    (true, 'K002', 'Sodikart RT8'),
    (true, 'K003', 'Sodikart RT8'),
    (true, 'K004', 'Sodikart RT8'),
    (true, 'K005', 'Sodikart RT8'),
    (true, 'K006', 'Sodikart RT8'),
    (true, 'K007', 'Sodikart RT8'),
    (true, 'K008', 'Sodikart RT8'),
    (true, 'K009', 'Sodikart RT8'),
    (true, 'K010', 'Sodikart RT8'),
    (true, 'K011', 'Sodikart RT8'),
    (true, 'K012', 'Sodikart RT8'),
    (false, 'K013', 'Sodikart RT8'),
    (false, 'K014', 'Sodikart RT8'),
    (false, 'K015', 'Sodikart RT8');
